---
reference-location: margin
bibliography: [ipm_vs_mcmc.bib, ../../research_proposal.bib]
csl: nature.csl
format:
  html: default
  pdf:
    margin-bottom: 1.87cm
    margin-right: 1.87cm
    margin-left: 1.87cm
    margin-top: 1.87cm
    fontsize: "12"
editor: source
---

Augustin Birot

Coping with climate change: Implications of a body mass increase^[shift is too vague since it can be either way] in yellow-bellied marmot over the last half century.

BACKGROUND: As a result of climate change, natural populations face rapid environmental variation with increased temperature, longer summers, and higher fluctuation from year to year making persistence more challenging than ever.
Several key traits of species such as body mass and size are expected to change in relation to the new environmental conditions.
Following Bergmann’s rule [@bergmannc1847], body mass and size are expected to decrease with increasing temperature to facilitate heat dissipation [@daufresne2009; @gardner_declining_2011].
However, body mass might also increase in response to global warming due to an increase in food availability or appearance of milder conditions^[can add the marmot paper as citation here also] [@guillemain2010; @sheridan2011; @yom-tov2008].
Furthermore, those changes in mass and size are expected to be correlated with a suite of behavioural and physiological traits and might aslo be associated with different survival and reproduction consequences^[not sure how the POLS fit here well without a lot more explanation].
The observed changes in traits with climate changes can be due to either evolution (*i.e.* changes in allele frequencies in response to selection, with younger individuals being better adapted to the new conditions) or phenotypic plasticity (*i.e.* genotype expressing different phenotypes depending on environmental conditions, or an individual adjusting to conditions within its life) [@charmantier_evolutionary_2014-1].
Knowing the importance and role of these two mechanisms in the observed changes in the traits of a species is key to understand the impact of climate changes and determine if and how a species can adapt to the new conditions. In Yellow-bellied marmots (*Marmota flaviventris*), a 10% increase in body mass over the past 50 years as been observed [@ozgul_coupled_2010] and was partly attributed to both evolution and plasticity. The reasons for such an increase and its consequences are however unclear.

STUDY SPECIES: Yellow-bellied marmots are ground-dwelling rodents inhabiting alpine habitats in western North America.
They are active above ground for approximately a third of the year (May-September) during which they need to reproduce and accumulate enough fat to survive hibernation for the remainder of the time [@armitage2014].
The significant increased in body mass observed over the past 50 years has first been hypothesized to be caused simply by milder winters and longer active seasons due to climate change allowing to reach higher masses [@ozgul_coupled_2010].
However, recent works on the same population (my MSc thesis) showed a strong genetic change of body mass over time which is not expected under the previous hypothesis raising the need to reconsider the evolutionary scenario behind this shift.
This study will be based on the long-term study of marmots in Colorado, USA, which started in 1962 and has followed over 5000 individuals from birth to death
This study presents extensive data at the individual level including morphological, behavioural and physiological as well as survival, reproduction and genetic relatedness information

OBJECTIVES: My PhD will explore three important research questions (RQ).^[running out of steam for this section since it is past 2300. also would be good to discuss since it is unclear what you mean]

- RQ1: What are the mechanisms of this increase? So is it due to an increase in the individual baseline? An increase in growing capacity? Or both? I will assess that by estimating individual specific intercept and slopes for body mass through their lifetime to compare them through cohorts.
Having strong variation in the intercept over time would indicate an increase of the individual baseline, and variation on the slopes represent an increase of their growing capacity.
- RQ2: Which modification in the environment, over the years, could have triggered this shift? I will test the impact of various weather variables (measured at the study site since 1978) on the body mass in order to target precise factors.
Then, I will test the effect of a combined variable (computed from principal component analysis) to check for a global weather effect on body mass.
- RQ3: What are the implications of this change in body condition on marmots' behavior, in line with the POLS? Using results from "flight initiation distance" experiment as a proxy of individual boldness [@ydenbergEconomicsFleeingPredators1986], I will test the impact of body mass, over time, on individual boldness.
Then, using "animal model" (i.e., mixed models assessing genetic variance from individual relatedness [@kruukEstimatingGeneticParameters2004]) I will test for variation of the individual's boldness genetic value over time.

SIGNIFICANCE: This research uses one of the most extensive natural population databases in the world to deepen our understanding of the genotype-phenotype-environment relationship.
It will provide crucial insights into how wild populations adapt to changing environments.
The project aims to illustrate the multimodal nature of both causes and consequences of this body mass increase, as we anticipate that no single hypothesis will fully explain the observed changes.
Instead, we expect that each hypothesis will account for part of the process, either complementing or conflicting with one another.
These findings will contribute valuable knowledge to both evolutionary biology and conservation biology, helping shape more effective conservation policies in the context of global climate change.






























<!-- ***Causes and consequences of the Yellow-Bellied Marmot's body mass shift in the last half century.***

**Background**: Natural selection shapes an organism's phenotype to optimize its fitness within its environment [@darwin_origin_1859]. When environmental conditions change, species typically respond in one of two ways: disperse or adapt [@charmantier_evolutionary_2014-1]. Adaptation occurs through **phenotypic plasticity**, where a genotype can express different phenotypes depending on environmental conditions, or **microevolution**, which involves shifts in allele frequencies within the population. While plasticity often provides a short-term solution, microevolution drives more permanent changes. Understanding how much each mechanism contributes to phenotypic changes is critical, especially in the context of climate change, where the consequences for populations could vary dramatically over time.

It is also crucial to understand that a Life-History Trait (LHT, i.e., a phenotypic trait that affects an individual's survival and reproduction) cannot evolve alone. Coevolution must be taken into account, and there is a growing need to conduct more multivariate analyses to understand evolutionary potential and identify potential constraints. This consideration is crucial to understand how a population can cope with environmental changes, particularly, again, in the context of climate change [@charmantier_evolutionary_2014; @gienappEvolutionaryDynamicsResponse2014].

Researchers have suggested that global warming could lead to a universal decrease in body size, in line with Bergmann's rule on heat dissipation [@bergmannc1847; @daufresne2009]. However, long-term evidence supporting this pattern is scarce [@gardner_declining_2011], and studies at higher latitudes have regularly produced contradictory findings [@guillemain2010; @yom-tov2008; @sheridan2011]. This contradictory pattern has been observed in a hibernating sciurid (Rodentia, Sciuridae), the Yellow-Bellied Marmots (YBM), *Marmota flaviventris*. A wild population in the Upper East River valley, Colorado, USA is the subject of the second longest-running wild mammal population studies in the world. It is also one of the most complete, with a tremendous quantity and variety of collected data. We have extensive data about marmot's life cycle, morphology, genetics, environment, etc. which allows for comprehensive analyses [more details in @armitage2014].

A significant body mass increase has been observed in this system during the last decades (1970s - 2010s). Initially, this was attributed to phenotypic plasticity resulting from milder environmental conditions and longer active season (i.e., spring/summer as marmots hibernates during the rest of the year) [@ozgul_coupled_2010]. However, recent work has raised questions about the use of **Integral Projection Model** [IPMs, i.e., a type of matrix projection model constructed on four major functions: survival, fecundity, development, and inheritance, @gonzalezIntegralProjectionModels2021] in making evolutionary inferences [@chevin_evolution_2015; @janeiro_towards_2017].

I reanalyzed this body mass shift, using quantitative genetic analysis, especially, **Animal Models**, which are a specific kind of mixed models. It uses a random individual effect linked with the population pedigree (i.e., parental links between each individual of the population) to decompose the phenotypic variance and estimates its genetic part [@kruukEstimatingGeneticParameters2004]. I worked in a Bayesian framework, using **MCMCglmms**, [@hadfield_mcmc_2010]. My preliminary research reveals a strong evolutionary signal alongside phenotypic plasticity. While the lengthening of the active season provides an ecological explanation for the observed plasticity, it does not account for the evolutionary changes. A longer active season should reduce selective pressure for larger body mass, as the death risks over hibernation would be lower. Thus, the aim of my PhD is to ***rethink the evolutionary drivers behind the observed body mass increase in the last half-century in a wild YBM population***. Then ***study the consequences of significant change in a LHT such as body mass in a hibernating species***.

{{< pagebreak >}}

**Research Questions (RQ) and Methods**: I will address two main research questions, each divided into several hypotheses with corresponding methodologies.

**RQ1**: *What are the causes of the observed body mass evolution?*

-   **Hypothesis 1**: Punctual extreme weather events have acted as selection bottlenecks, favoring heavier individuals in the population.

    -   **Methodology 1**: I will analyze extreme weather events occurrences at study sites and investigate their links with population fluctuations and mean body mass' genetic values over the study period.

-   **Hypothesis 2**: More frequent drought events, due to global warming, increase the proportion of dry vegetation, enhancing selection for larger individuals able to consume a more fibrous diet thanks to a longer Mean Retention Time (MRT) [@armitage2014].

    -   **Methodology 2**: I will study marmots' diet composition over the years to evaluate changes in vegetation quality and selection.

-   **Hypothesis 3**: Larger individuals will be favored by natural selection for their ability to fend off smaller predators such as Long-Tailed Weasels (*Mustela frenata*) and American Marten (*Martes americana*) [@armitage2014].

    -   **Methodology 3**: I will examine predators population dynamics and species composition and compare that to the recorded causes of marmot mortality over the study period.

**RQ2**: *What are the short- and long-term consequences of this LHT shift?*

-   **Hypothesis 4**: A significant shift in body mass, combined with environmental changes, will alter the life cycle of this hibernating species.

    -   **Methodology 4**: I will investigate changes in the active season/hibernation length balance and examine potential correlations with body mass and environmental factors.

-   **Hypothesis 5**: A shift in body condition will result in behavioral changes at the individual level.

    -   **Methodology 5**: I will assess changes in individual behavior by analyzing boldness data collected through Flight Initiation Distance (FID) experiments over the study period and test for links with body mass.

**Significance and Impact**: This research uses one of the most extensive natural population databases in the world to deepen our understanding of the genotype-phenotype-environment relationship. It will provide crucial insights into how wild populations adapt to changing environments. The project aims to illustrate the multimodal nature of both causes and consequences of this body mass increase, as we anticipate that no single hypothesis will fully explain the observed changes. Instead, we expect that each hypothesis will account for part of the process, either complementing or conflicting with one another. These findings will contribute valuable knowledge to the field of conservation biology, helping shape more effective conservation policies in the context of global climate change. -->

{{< pagebreak >}}

#### References

::: {refs}
:::
