---
bibliography: [ipm_vs_mcmc.bib]
csl: american-statistical-association.csl
format: pdf
editor: source
---

Augustin Birot

***Causes and consequences of the Yellow-Bellied Marmot's body mass shift in the last half century.***

**Background**: Natural selection shapes an organism's phenotype to optimize its fitness within its environment [@darwin_origin_1859]. When environmental conditions change, species typically respond in one of two ways: disperse or adapt [@charmantier_evolutionary_2014-1]. Adaptation occurs through **phenotypic plasticity**, where a genotype can express different phenotypes depending on environmental conditions, or **microevolution**, which involves shifts in allele frequencies within the population. While plasticity often provides a short-term solution, microevolution drives more permanent changes. Understanding how much each mechanism contributes to phenotypic changes is critical, especially in the context of climate change, where the consequences for populations could vary dramatically over time.

Researchers have suggested that global warming could lead to a universal decrease in body size, in line with Bergmann's rule on heat dissipation [@bergmannc1847; @daufresne2009]. However, long-term evidence supporting this pattern is scarce [@gardner_declining_2011], and studies at higher latitudes have regularly produced contradictory findings [@guillemain2010; @yom-tov2008; @sheridan2011]. In Yellow-Bellied Marmots (YBM), *Marmota flaviventris*, which are the subject of one of the longest-running wild mammal population studies [more details in @armitage2014], we observe an increase in body mass in the last decades (1970s - 2010s). Initially, this shift was attributed to phenotypic plasticity resulting from milder environmental conditions and longer active season [@ozgul_coupled_2010].

However, recent work has raised question about the use of **Integral Projection Model** (IPMs) in making evolutionary inferences [@chevin_evolution_2015; @janeiro_towards_2017]. My preliminary research, using quantitative genetic analysis, especially the **Animal Model**, in a Bayesian framework [**MCMCglmm**, @hadfield_mcmc_2010], reveals a strong evolutionary signal alongside phenotypic plasticity. While the lengthening of the active season provides an ecological explanation for the observed plasticity, it does not account for the evolutionary changes. A longer active season should reduce selective pressure for larger body mass. Thus, the aim of my PhD is to ***rethink the evolutionary drivers behind the observed body mass increase in the last half-century in a wild YBM population***. Then ***study the consequences of significant change in a life-history trait such as body mass in a hibernating species***.

**Research Questions (RQ) and Methods**: I will address two main research questions, each divided into several hypotheses with corresponding methodologies.

**RQ1**: *What are the causes of the observed body mass evolution?*

-   **Hypothesis 1**: Punctual extreme weather events have acted as selection bottlenecks, favouring heavier individuals in the population.

    -   **Methodology 1**: I will analyze extreme weather events occurences at the study sites and investigate their link with population fluctuations and mean body mass' genetic values over the study period.

-   **Hypothesis 2**: Drought events, which have become more frequent with global warming, increase the proportion of dry vegetation, enhancing selection for larger individuals able consume a more fibrous diet due to longer Mean Retention Time (MRT) [@armitage2014].

    -   **Methodology 2**: I will study marmots' diet composition over the years to evaluate changes in vegetation quality and selection.

-   **Hypothesis 3**: Larger individuals will be favoured by natural selection as they are better able to fend off smaller predators such as Long-Tailed Weasels (*Mustela frenata*) and American Marten (*Martes americana*) [@armitage2014].

    -   **Methodology 3**: I will examine predators population dynamics and species composition and compare that to the recorded causes of marmot mortality over the study period.

**RQ2**: *What are the short- and long-term consequences of this shift in a Life-History Trait (LHT)?*

-   **Hypothesis 4**: A significant shift in body mass, combined with environmental changes, will alter the life cycle of this hibernating species.

    -   **Methodology 4**: I will investigate changes in the active season/hibernation length balance and examine potential correlations with body mass and environmental factors.

-   **Hypothesis 5**: A shift in body condition will result in behavioural changes at the individual level.

    -   **Methodology 5**: I will assess changes in individual behavior by analysing boldness data collected through Flight Initiation Distance (FID) experiments over the study period and test for link with body mass.

**Significance and Impact**: This research uses one of the most extensive natural population databases in the world to deepen our understanding of the genotype-phenotype-environment relationship. This work will provide crucial insights into how wild populations adapt to changing environments. These findings will contribute valuable knowledge to the field of conservation biology, helping shape more effective conservation policies in the context of global climate change.

{{< pagebreak >}}

#### References

::: {refs}
:::
